apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: apt-jmeter
  name: apt-jmeter
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: apt-jmeter:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/fgiloux/auto-perf-test.git
    contextDir: jmeter/container
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: java-centos-openjdk8-jdk:1.4
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: R5N6fqeAGHmIx6db7Vhx
    type: GitHub
  - generic:
      secret: TxtCDPVPl-R_4todBNBb
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
