apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: camel-amq-fakeapp
    group: org.fgiloux.sandbox
    provider: fabric8
    version: 1.0-SNAPSHOT
  name: camel-amq-fakeapp
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/perftest/camel-amq-fakeapp:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
