apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: camel-amq-fakeapp
    group: org.fgiloux.sandbox
    provider: fabric8
    version: 1.0-SNAPSHOT
  name: camel-amq-fakeapp-s2i
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: camel-amq-fakeapp:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: fabric8/s2i-java:2.1
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0
