apiVersion: v1
data:
  application.properties: |
    # Binding health checks to an internal port
    # management.port=8081

    # disable all management enpoints except health
    # endpoints.enabled=false
    # endpoints.health.enabled=true

    # TO BE CHANGED
    logging.config=classpath:logback.xml

    # The name of the Camel app
    # camel.springboot.name=fakeApp

    # Keeps the application alive
    # camel.springboot.main-run-controller=true

    # AMQP connection configuration (can be overridden in Openshift by injecting environment variables into the deployment configuration)
    # Passwords must not be populated in this file. They can be injected using secrets. The fields are here only for documentation purpose.
    # amqp.scheme=amqps
    # amqp.host=localhost

    # TO BE CHANGED
    amqp.host=messaging-perftest.apps.sandbox.com
    # amqp.port=443

    amqp.options.transport.trustStoreLocation=/opt/broker-jks/amqp.jks
    # amqp.options.transport.verifyHost=false
    amqp.options.disableReplyTo=true
    amqp.options.acknowledgementModeName=CLIENT_ACKNOWLEDGE

    # message.input=input.queue
    # message.output=output.queue

    # Processing
    # load in fraction of CPU cores available (capped to 1)
    # processing.load=0.8
    # duration in ms
    # processing.duration=200
    # distribution is normal/Gaussian: Random.nextGaussian() x processing.duration.deviation + processing.duration
    # with a deviation of 100, this means that 70% of values will fall between duration +/- 100, in other words between 400 and 600 milliseconds
    # if process.duration is set to 500.
    # choosing a value of 0 means no deviation and the duration or load is always the same.
    # processing.duration.deviation=0
    # processing.load.deviation=0
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: camel-amq-fakeapp-props
